name: Build, Transfer, Load, and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend image
        run: |
          docker build --platform linux/amd64 --build-arg NEXT_PUBLIC_BACKEND_URL="https://team12.serverquake.com/api" -t borsibaar-team12-frontend:latest ./frontend
          docker save borsibaar-team12-frontend:latest > frontend.tar

      - name: Build backend image
        run: |
          docker build -t borsibaar-team12-backend:latest ./backend
          docker save borsibaar-team12-backend:latest > backend.tar
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Copy images to server
        run: |
          scp -o StrictHostKeyChecking=no frontend.tar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USER }}/team12/opt/deployer-docker/
          scp -o StrictHostKeyChecking=no backend.tar ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SSH_USER }}/team12/opt/deployer-docker/

      - name: SSH and load images into registry
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} "
            cd /home/${{ secrets.SSH_USER }}/team12/opt/deployer-docker &&
            docker load < frontend.tar &&
            docker load < backend.tar &&
            docker tag borsibaar-team12-frontend:latest localhost:5000/borsibaar-team12-frontend:latest &&
            docker tag borsibaar-team12-backend:latest localhost:5000/borsibaar-team12-backend:latest &&
            docker push localhost:5000/borsibaar-team12-frontend:latest &&
            docker push localhost:5000/borsibaar-team12-backend:latest &&
            docker-compose pull &&
            docker-compose up -d
          "